apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2  # run 2 pods
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: harnesstraining/dotnet-frontend:latest
        ports:
        - containerPort: 80
