apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 8080  # exposed port on the VM
  selector:
    app: react-app
