pipeline:
  identifier: Build_MyHarness_1743230819494
  name: Build MyHarness
  orgIdentifier: default
  projectIdentifier: Harness_demo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Matta_Chenna_Rao
        repoName: MyHarness
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: Install Dependencies
                  type: Run
                  spec:
                    shell: Sh
                    image: node:18
                    command: |
                      echo "Checking Node.js & npm versions..."
                      node -v
                      npm -v
                      npm install
                  timeout: 10m
              - step:
                  identifier: build
                  name: Build Project
                  type: Run
                  spec:
                    shell: Sh
                    image: node:18
                    command: npm run build
                  timeout: 10m
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_2
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: account.harnessImage
                    repo: chenna12356/harness-demo
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
