pipeline:
  name: Build MyHarness
  identifier: Build_MyHarness_1743240779490
  projectIdentifier: Harness_demo
  orgIdentifier: default
  stages:
    - stage:
        name: MyHarness
        identifier: MyHarness
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: chenna12356/harness-demo
                    tags:
                      - latest
        delegateSelectors:
          - docker-delegate
  properties:
    ci:
      codebase:
        connectorRef: Matta_Chenna_Rao
        repoName: MyHarness
        build: <+input>
